name: safe_drive_monitor
description: A mobile app to help monitor driving habits
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  sensors_plus: ^6.1.1
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 